# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'uiux.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1051, 701)
        MainWindow.setStyleSheet("background-color; white;")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.map = QtWidgets.QLabel(self.centralwidget)
        self.map.setEnabled(True)
        self.map.setGeometry(QtCore.QRect(130, 0, 791, 531))
        self.map.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.map.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.map.setText("")
        self.map.setPixmap(QtGui.QPixmap("app/sfdnskfjsdnf.png"))
        self.map.setScaledContents(True)
        self.map.setIndent(0)
        self.map.setObjectName("map")
        self.start_point = QtWidgets.QComboBox(self.centralwidget)
        self.start_point.setGeometry(QtCore.QRect(230, 550, 161, 25))
        self.start_point.setObjectName("start_point")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(160, 550, 67, 17))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(690, 550, 67, 17))
        self.label_2.setObjectName("label_2")
        self.end_point = QtWidgets.QComboBox(self.centralwidget)
        self.end_point.setGeometry(QtCore.QRect(760, 550, 161, 25))
        self.end_point.setObjectName("end_point")
        self.add_node_button = QtWidgets.QPushButton(self.centralwidget)
        self.add_node_button.setGeometry(QtCore.QRect(10, 10, 101, 91))
        self.add_node_button.setObjectName("add_node_button")
        self.build_way_button = QtWidgets.QPushButton(self.centralwidget)
        self.build_way_button.setGeometry(QtCore.QRect(450, 580, 191, 61))
        self.build_way_button.setObjectName("build_way_button")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(430, 550, 231, 17))
        self.label_3.setObjectName("label_3")
        self.path = QtWidgets.QLabel(self.centralwidget)
        self.path.setGeometry(QtCore.QRect(120, 650, 441, 17))
        self.path.setObjectName("path")
        self.path.setVisible(False)
        self.distance = QtWidgets.QLabel(self.centralwidget)
        self.distance.setGeometry(QtCore.QRect(120, 600, 181, 17))
        self.distance.setObjectName("distance")
        self.distance.setVisible(False)

        self.time = QtWidgets.QLabel(self.centralwidget)
        self.time.setGeometry(QtCore.QRect(120, 620, 241, 17))
        self.time.setObjectName("time")
        self.time.setVisible(False)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "FIndWayLab"))
        self.label.setText(_translate("MainWindow", "Початок:"))
        self.label_2.setText(_translate("MainWindow", "Кінець:"))
        self.add_node_button.setText(_translate("MainWindow", "Додати\n"
"вершину"))
        self.build_way_button.setText(_translate("MainWindow", "Побудувати шлях"))
        self.label_3.setText(_translate("MainWindow", "Довжина шляху: "))
        self.path.setText(_translate("MainWindow", "Шлях:"))
        self.distance.setText(_translate("MainWindow", "Довжина шляху: "))
        self.time.setText(_translate("MainWindow", "Витрачено часу: "))
